version: '3'

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: medication-management_local
      POSTGRES_USER: medication-management_local
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data-medication-management:/var/lib/postgresql/data

volumes:
  db-data-medication-management: